### ISSUE TITLE
Implementing this module on a greyscale image.

### ISSUE THREAD

**Issue by jjspergel** [0mar/weighted-distance-transform#2]
Hi!

What parts of the code need to be changed in order to calculate the weighted  distance transform  on  an image on values [0-1]?  Or would it be better to convert this image into an RGB image based on the rules pre-established? Thank you for your  help!

**Comment by 0mar** [comment]
Hey!

Very little, I would say. 

At `wdt.py:32` (in current commit a1f55f8) the image values are converted from `uint8` values between 0 and 255 to `float64` values between 0 and 1. If your image is already properly scaled, then I guess all you have to do is omit that step.

Moreover, if you are already working with greyscale images, you can alter lines `wdt.py:34-38` and drop in your array there. The RBG is being converted to a greyscale image after object detection anyway, to obtain a cost field.

Hope this helps!

**Comment by 0mar** [comment]
I'm closing this, but let me know if you want any more pointers!

**Comment by jjspergel** [comment]
I'm still tinkering with it to get it to work, but thank you!
